# Generated by Django 4.2.5 on 2023-09-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(max_length=50)),
                ('president', models.CharField(blank=True, max_length=100, null=True)),
                ('coach', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('top_buy_tr', models.CharField(blank=True, max_length=100, null=True)),
                ('top_sell_tr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=50)),
                ('selling_cost', models.CharField(max_length=50)),
                ('season', models.CharField(default='22-23', max_length=50)),
                ('after_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.club')),
                ('before_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='asosiy.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.player')),
            ],
        ),
    ]
